### ISSUE TITLE
NPM installation not working - tsconfig.json not recognizing the library

### ISSUE THREAD

**Issue by jgonzalezalbisu** [steambap/xpath-to-selector#3]
Hi!
When executing `npm install --save-dev css-to-selector` I get an error saying the library doesn't exists.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/css-to-selector - Not found
npm ERR! 404 
npm ERR! 404  'css-to-selector@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I presume that this is incorrect as the package name is `xpath-to-selector`.

Also I've found that after installing it, I don't get my `tsconfig.json` to recognize the library (below is the error).
![image](https://user-images.githubusercontent.com/23585745/228059993-0a7587f7-de2d-4cae-97bd-d622bacabefd.png) 

Similar problem happens when I try to import the module to any of my files by adding `import x2c from "xpath-to-selector";`
![image](https://user-images.githubusercontent.com/23585745/228060502-b8f32e32-63b0-4a26-9e2e-7b3813815a80.png)

**Comment by steambap** [comment]
Thank you for pointing this out. I forget to build before publish last time. I have publish a version v1.1.3 on npm.

Also thank you for find out the typo in readme.

**Comment by jgonzalezalbisu** [comment]
Thanks @steambap ! it's working now.
